export interface AIModelCatalogItem {
  id: string;
  name: string;
  provider: string;
  category: "language" | "vision" | "code" | "embedding" | "image";
  contextWindow?: number;
  description: string;
}

export const MODELS_CATALOG: AIModelCatalogItem[] = [
  // --- OpenAI (18) ---
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    category: "vision",
    contextWindow: 128000,
    description: "Flagship multimodal model powering high-speed text and vision intelligence.",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "OpenAI",
    category: "vision",
    contextWindow: 128000,
    description: "Cost-efficient lightweight multimodal model for everyday workloads.",
  },
  {
    id: "gpt-4-turbo",
    name: "GPT-4 Turbo",
    provider: "OpenAI",
    category: "language",
    contextWindow: 128000,
    description: "Advanced reasoning model with deep analysis capabilities and updated knowledge.",
  },
  {
    id: "gpt-4",
    name: "GPT-4",
    provider: "OpenAI",
    category: "language",
    contextWindow: 32768,
    description: "Original groundbreaking frontier model for complex reasoning and synthesis.",
  },
  {
    id: "gpt-3.5-turbo",
    name: "GPT-3.5 Turbo",
    provider: "OpenAI",
    category: "language",
    contextWindow: 16385,
    description: "Ultra-fast benchmark model for general text processing and chat.",
  },
  {
    id: "o1",
    name: "OpenAI o1",
    provider: "OpenAI",
    category: "language",
    contextWindow: 200000,
    description: "Reasoning model trained with reinforcement learning for heavy science and math.",
  },
  {
    id: "o1-mini",
    name: "OpenAI o1-mini",
    provider: "OpenAI",
    category: "code",
    contextWindow: 128000,
    description: "Fast reasoning model optimized for STEM and code generation.",
  },
  {
    id: "o3",
    name: "OpenAI o3",
    provider: "OpenAI",
    category: "language",
    contextWindow: 200000,
    description: "Next-gen frontier reasoning system setting new evaluation benchmarks.",
  },
  {
    id: "o3-mini",
    name: "OpenAI o3-mini",
    provider: "OpenAI",
    category: "code",
    contextWindow: 200000,
    description: "High-speed reasoning model tailored for complex programming and logic tasks.",
  },
  {
    id: "text-embedding-3-small",
    name: "Text Embedding 3 Small",
    provider: "OpenAI",
    category: "embedding",
    contextWindow: 8191,
    description: "Highly efficient embedding model for vector search and retrieval.",
  },
  {
    id: "text-embedding-3-large",
    name: "Text Embedding 3 Large",
    provider: "OpenAI",
    category: "embedding",
    contextWindow: 8191,
    description: "High-dimensional embedding model for enterprise semantic search.",
  },
  {
    id: "text-embedding-ada-002",
    name: "Ada 002 Embedding",
    provider: "OpenAI",
    category: "embedding",
    contextWindow: 8191,
    description: "Legacy industry-standard embedding model for semantic similarity.",
  },
  {
    id: "dall-e-3",
    name: "DALL·E 3",
    provider: "OpenAI",
    category: "image",
    description: "State-of-the-art image generation model with strict prompt adherence.",
  },
  {
    id: "dall-e-2",
    name: "DALL·E 2",
    provider: "OpenAI",
    category: "image",
    description: "Photorealistic image generation and editing model.",
  },
  {
    id: "whisper-1",
    name: "Whisper v3",
    provider: "OpenAI",
    category: "language",
    description: "Robust automatic speech recognition and translation model.",
  },
  {
    id: "gpt-4o-realtime",
    name: "GPT-4o Realtime",
    provider: "OpenAI",
    category: "language",
    contextWindow: 128000,
    description: "Low-latency speech-to-speech multimodal API model.",
  },
  {
    id: "gpt-4-vision-preview",
    name: "GPT-4 Vision",
    provider: "OpenAI",
    category: "vision",
    contextWindow: 128000,
    description: "Visual understanding model capability integrated into GPT-4.",
  },
  {
    id: "gpt-4o-audio-preview",
    name: "GPT-4o Audio",
    provider: "OpenAI",
    category: "language",
    contextWindow: 128000,
    description: "Native audio processing variant of GPT-4o.",
  },

  // --- Anthropic (10) ---
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    category: "code",
    contextWindow: 200000,
    description: "Industry-leading model for coding, complex reasoning, and nuance.",
  },
  {
    id: "claude-3-5-haiku",
    name: "Claude 3.5 Haiku",
    provider: "Anthropic",
    category: "language",
    contextWindow: 200000,
    description: "Lightning-fast model outperforming previous generation flagship models.",
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus",
    provider: "Anthropic",
    category: "language",
    contextWindow: 200000,
    description: "Deep analysis model designed for highly complex open-ended tasks.",
  },
  {
    id: "claude-3-sonnet",
    name: "Claude 3 Sonnet",
    provider: "Anthropic",
    category: "language",
    contextWindow: 200000,
    description: "Balanced performance and speed for enterprise applications.",
  },
  {
    id: "claude-3-haiku",
    name: "Claude 3 Haiku",
    provider: "Anthropic",
    category: "language",
    contextWindow: 200000,
    description: "Compact model built for instant responses and lightweight automation.",
  },
  {
    id: "claude-2.1",
    name: "Claude 2.1",
    provider: "Anthropic",
    category: "language",
    contextWindow: 200000,
    description: "Enterprise model featuring reduced hallucination rates and large context window.",
  },
  {
    id: "claude-2.0",
    name: "Claude 2.0",
    provider: "Anthropic",
    category: "language",
    contextWindow: 100000,
    description: "Second generation foundation model with strong reasoning abilities.",
  },
  {
    id: "claude-instant-1.2",
    name: "Claude Instant 1.2",
    provider: "Anthropic",
    category: "language",
    contextWindow: 100000,
    description: "High-speed lightweight model for quick dialogue and extraction.",
  },
  {
    id: "claude-3-5-sonnet-v2",
    name: "Claude 3.5 Sonnet v2",
    provider: "Anthropic",
    category: "code",
    contextWindow: 200000,
    description: "Updated Claude 3.5 Sonnet model with enhanced computer use capabilities.",
  },
  {
    id: "claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet",
    provider: "Anthropic",
    category: "language",
    contextWindow: 200000,
    description: "Hybrid reasoning model combining instant response and deep thinking.",
  },

  // --- Google (16) ---
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    category: "vision",
    contextWindow: 1000000,
    description: "Next-generation multimodal model delivering fast latency and 1M context window.",
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash Lite",
    provider: "Google",
    category: "language",
    contextWindow: 1000000,
    description: "Ultra-cost-effective Gemini 2.0 model optimized for throughput.",
  },
  {
    id: "gemini-2.0-pro-exp",
    name: "Gemini 2.0 Pro",
    provider: "Google",
    category: "language",
    contextWindow: 2000000,
    description: "Google's top-tier reasoning and coding model with 2M token context window.",
  },
  {
    id: "gemini-1.5-pro",
    name: "Gemini 1.5 Pro",
    provider: "Google",
    category: "vision",
    contextWindow: 2000000,
    description: "Enterprise multimodal model capable of analyzing video, audio, and large repos.",
  },
  {
    id: "gemini-1.5-flash",
    name: "Gemini 1.5 Flash",
    provider: "Google",
    category: "vision",
    contextWindow: 1000000,
    description: "High-speed multimodal workhorse for high-frequency applications.",
  },
  {
    id: "gemini-1.5-flash-8b",
    name: "Gemini 1.5 Flash 8B",
    provider: "Google",
    category: "language",
    contextWindow: 1000000,
    description: "Small footprint variant designed for high-volume text tasks.",
  },
  {
    id: "gemini-1.0-pro",
    name: "Gemini 1.0 Pro",
    provider: "Google",
    category: "language",
    contextWindow: 32768,
    description: "First-generation multimodal model for natural language generation.",
  },
  {
    id: "gemma-2-27b",
    name: "Gemma 2 27B",
    provider: "Google",
    category: "language",
    contextWindow: 8192,
    description: "Open weight 27B parameter model competing with larger proprietary systems.",
  },
  {
    id: "gemma-2-9b",
    name: "Gemma 2 9B",
    provider: "Google",
    category: "language",
    contextWindow: 8192,
    description: "Efficient open weights model tailored for local and edge deployment.",
  },
  {
    id: "gemma-2-2b",
    name: "Gemma 2 2B",
    provider: "Google",
    category: "language",
    contextWindow: 8192,
    description: "Ultra-compact open model optimized for lightweight hardware.",
  },
  {
    id: "gemma-7b",
    name: "Gemma 7B",
    provider: "Google",
    category: "language",
    contextWindow: 8192,
    description: "First generation open model trained on 6 trillion tokens.",
  },
  {
    id: "imagen-3",
    name: "Imagen 3",
    provider: "Google",
    category: "image",
    description: "Google's highest-quality text-to-image synthesis model.",
  },
  {
    id: "imagen-2",
    name: "Imagen 2",
    provider: "Google",
    category: "image",
    description: "Photorealistic image generation model for enterprise applications.",
  },
  {
    id: "text-embedding-004",
    name: "Text Embedding 004",
    provider: "Google",
    category: "embedding",
    contextWindow: 2048,
    description: "Google's latest semantic text embedding model.",
  },
  {
    id: "multimodal-embedding-001",
    name: "Multimodal Embedding 001",
    provider: "Google",
    category: "embedding",
    contextWindow: 2048,
    description: "Joint text-and-image embedding space for visual search.",
  },
  {
    id: "veo-2",
    name: "Veo 2",
    provider: "Google",
    category: "vision",
    description: "Generative high-definition video synthesis model.",
  },

  // --- Meta (14) ---
  {
    id: "llama-3.3-70b",
    name: "Llama 3.3 70B",
    provider: "Meta",
    category: "language",
    contextWindow: 128000,
    description:
      "Open 70B parameter flagship model delivering performance matching Llama 3.1 405B.",
  },
  {
    id: "llama-3.1-405b",
    name: "Llama 3.1 405B",
    provider: "Meta",
    category: "language",
    contextWindow: 128000,
    description: "World's largest open foundation model with frontier capabilities.",
  },
  {
    id: "llama-3.1-70b",
    name: "Llama 3.1 70B",
    provider: "Meta",
    category: "language",
    contextWindow: 128000,
    description: "Highly capable open source LLM for complex logic, math, and code.",
  },
  {
    id: "llama-3.1-8b",
    name: "Llama 3.1 8B",
    provider: "Meta",
    category: "language",
    contextWindow: 128000,
    description: "High-speed compact model suitable for fine-tuning and fast inference.",
  },
  {
    id: "llama-3.2-90b-vision",
    name: "Llama 3.2 90B Vision",
    provider: "Meta",
    category: "vision",
    contextWindow: 128000,
    description: "Multimodal Llama variant capable of high-level visual reasoning.",
  },
  {
    id: "llama-3.2-11b-vision",
    name: "Llama 3.2 11B Vision",
    provider: "Meta",
    category: "vision",
    contextWindow: 128000,
    description: "Lightweight visual understanding model for diagram and document analysis.",
  },
  {
    id: "llama-3.2-3b",
    name: "Llama 3.2 3B",
    provider: "Meta",
    category: "language",
    contextWindow: 128000,
    description: "Mobile-optimized lightweight model for on-device applications.",
  },
  {
    id: "llama-3.2-1b",
    name: "Llama 3.2 1B",
    provider: "Meta",
    category: "language",
    contextWindow: 128000,
    description: "Ultra-compact Llama model for low-latency edge deployment.",
  },
  {
    id: "llama-3-70b",
    name: "Llama 3 70B",
    provider: "Meta",
    category: "language",
    contextWindow: 8192,
    description: "Base Llama 3 flagship model for general language tasks.",
  },
  {
    id: "llama-3-8b",
    name: "Llama 3 8B",
    provider: "Meta",
    category: "language",
    contextWindow: 8192,
    description: "Base Llama 3 8B parameter model.",
  },
  {
    id: "code-llama-70b",
    name: "Code Llama 70B",
    provider: "Meta",
    category: "code",
    contextWindow: 16384,
    description: "Specialized programming model fine-tuned for code generation and debugging.",
  },
  {
    id: "code-llama-34b",
    name: "Code Llama 34B",
    provider: "Meta",
    category: "code",
    contextWindow: 16384,
    description: "Intermediate programming model for software engineering.",
  },
  {
    id: "llama-guard-3",
    name: "Llama Guard 3",
    provider: "Meta",
    category: "language",
    contextWindow: 128000,
    description: "Safety classification model for content moderation.",
  },
  {
    id: "llama-2-70b",
    name: "Llama 2 70B",
    provider: "Meta",
    category: "language",
    contextWindow: 4096,
    description: "Predecessor open foundation model from Meta.",
  },

  // --- Mistral AI (12) ---
  {
    id: "mistral-large-2",
    name: "Mistral Large 2",
    provider: "Mistral AI",
    category: "code",
    contextWindow: 128000,
    description: "123B parameter flagship model with exceptional code and math performance.",
  },
  {
    id: "mistral-large",
    name: "Mistral Large",
    provider: "Mistral AI",
    category: "language",
    contextWindow: 32000,
    description: "Top-tier commercial model with multi-lingual reasoning.",
  },
  {
    id: "mistral-medium",
    name: "Mistral Medium",
    provider: "Mistral AI",
    category: "language",
    contextWindow: 32000,
    description: "Balanced commercial model for business applications.",
  },
  {
    id: "mistral-small",
    name: "Mistral Small",
    provider: "Mistral AI",
    category: "language",
    contextWindow: 32000,
    description: "Fast, low-cost commercial model for high-volume endpoints.",
  },
  {
    id: "mistral-nemo",
    name: "Mistral NeMo",
    provider: "Mistral AI",
    category: "language",
    contextWindow: 128000,
    description: "12B parameter model built in collaboration with NVIDIA.",
  },
  {
    id: "codestral",
    name: "Codestral",
    provider: "Mistral AI",
    category: "code",
    contextWindow: 32000,
    description: "22B open-weight code generation model supporting 80+ programming languages.",
  },
  {
    id: "codestral-mamba",
    name: "Codestral Mamba",
    provider: "Mistral AI",
    category: "code",
    contextWindow: 256000,
    description: "State-space architecture model offering linear time inference for code.",
  },
  {
    id: "mixtral-8x22b",
    name: "Mixtral 8x22B",
    provider: "Mistral AI",
    category: "language",
    contextWindow: 65536,
    description: "High-capacity sparse mixture-of-experts model.",
  },
  {
    id: "mixtral-8x7b",
    name: "Mixtral 8x7B",
    provider: "Mistral AI",
    category: "language",
    contextWindow: 32000,
    description: "Pioneering sparse MoE model outperforming Llama 2 70B.",
  },
  {
    id: "pixtral-12b",
    name: "Pixtral 12B",
    provider: "Mistral AI",
    category: "vision",
    contextWindow: 128000,
    description: "Native vision-language open model from Mistral AI.",
  },
  {
    id: "pixtral-large",
    name: "Pixtral Large",
    provider: "Mistral AI",
    category: "vision",
    contextWindow: 128000,
    description: "Enterprise multimodal model with document and image synthesis.",
  },
  {
    id: "mistral-embed",
    name: "Mistral Embed",
    provider: "Mistral AI",
    category: "embedding",
    contextWindow: 8192,
    description: "High-quality text embedding model.",
  },

  // --- Qwen / Alibaba Cloud (14) ---
  {
    id: "qwen3.5-omni-7b",
    name: "Qwen3.5-Omni 7B",
    provider: "Qwen",
    category: "vision",
    contextWindow: 32768,
    description: "Real-time multimodal speech and vision model.",
  },
  {
    id: "qwen2.5-max",
    name: "Qwen 2.5 Max",
    provider: "Qwen",
    category: "language",
    contextWindow: 128000,
    description: "Alibaba's largest flagship intelligence model competing with top-tier LLMs.",
  },
  {
    id: "qwen2.5-72b",
    name: "Qwen 2.5 72B",
    provider: "Qwen",
    category: "language",
    contextWindow: 128000,
    description: "Open 72B model excelling at mathematics, code, and non-English tasks.",
  },
  {
    id: "qwen2.5-32b",
    name: "Qwen 2.5 32B",
    provider: "Qwen",
    category: "language",
    contextWindow: 128000,
    description: "Sweet-spot open weights model for complex logic and retrieval.",
  },
  {
    id: "qwen2.5-14b",
    name: "Qwen 2.5 14B",
    provider: "Qwen",
    category: "language",
    contextWindow: 128000,
    description: "Medium-sized open weight language model.",
  },
  {
    id: "qwen2.5-7b",
    name: "Qwen 2.5 7B",
    provider: "Qwen",
    category: "language",
    contextWindow: 128000,
    description: "Compact language model for local deployment.",
  },
  {
    id: "qwen2.5-coder-32b",
    name: "Qwen 2.5 Coder 32B",
    provider: "Qwen",
    category: "code",
    contextWindow: 128000,
    description: "State-of-the-art open code generation model matching Sonnet 3.5 levels.",
  },
  {
    id: "qwen2.5-coder-7b",
    name: "Qwen 2.5 Coder 7B",
    provider: "Qwen",
    category: "code",
    contextWindow: 128000,
    description: "Lightweight code completion model.",
  },
  {
    id: "qwen2.5-vl-72b",
    name: "Qwen 2.5 VL 72B",
    provider: "Qwen",
    category: "vision",
    contextWindow: 128000,
    description: "High-resolution vision-language model for document AI and chart reading.",
  },
  {
    id: "qwen2.5-vl-7b",
    name: "Qwen 2.5 VL 7B",
    provider: "Qwen",
    category: "vision",
    contextWindow: 128000,
    description: "Compact vision model for mobile and edge application.",
  },
  {
    id: "qwen-2-72b",
    name: "Qwen 2 72B",
    provider: "Qwen",
    category: "language",
    contextWindow: 32768,
    description: "Predecessor flagship open language model.",
  },
  {
    id: "qwen-1.5-110b",
    name: "Qwen 1.5 110B",
    provider: "Qwen",
    category: "language",
    contextWindow: 32768,
    description: "Large-scale parameter model from earlier Qwen generation.",
  },
  {
    id: "qwen2.5-math-72b",
    name: "Qwen 2.5 Math 72B",
    provider: "Qwen",
    category: "language",
    contextWindow: 4096,
    description: "Specialized mathematical problem solver model.",
  },
  {
    id: "qwen-qwq-32b-preview",
    name: "QwQ 32B Preview",
    provider: "Qwen",
    category: "language",
    contextWindow: 32768,
    description: "Experimental reasoning model focusing on chain-of-thought processing.",
  },

  // --- NVIDIA (10) ---
  {
    id: "nemotron-4-340b",
    name: "Nemotron-4 340B",
    provider: "NVIDIA",
    category: "language",
    contextWindow: 4096,
    description: "Massive open model designed for synthetic data generation.",
  },
  {
    id: "nemotron-3-22b",
    name: "Nemotron-3 22B",
    provider: "NVIDIA",
    category: "language",
    contextWindow: 4096,
    description: "Enterprise model optimized for TensorRT-LLM inference.",
  },
  {
    id: "llama-3.1-nemotron-70b",
    name: "Llama 3.1 Nemotron 70B",
    provider: "NVIDIA",
    category: "language",
    contextWindow: 128000,
    description: "NVIDIA fine-tuned Llama model setting alignment benchmarks.",
  },
  {
    id: "nv-embed-v1",
    name: "NV-Embed v1",
    provider: "NVIDIA",
    category: "embedding",
    contextWindow: 32768,
    description: "Top-ranking open text embedding model on MTEB.",
  },
  {
    id: "nv-rerank-v1",
    name: "NV-Rerank v1",
    provider: "NVIDIA",
    category: "embedding",
    contextWindow: 4096,
    description: "Cross-encoder model for high-precision retrieval reranking.",
  },
  {
    id: "edify-image",
    name: "Edify Image",
    provider: "NVIDIA",
    category: "image",
    description: "3D-aware generative image model for synthetic data creation.",
  },
  {
    id: "edify-3d",
    name: "Edify 3D",
    provider: "NVIDIA",
    category: "image",
    description: "Generative AI model producing high-quality 3D assets.",
  },
  {
    id: "nemotron-mini-4b",
    name: "Nemotron Mini 4B",
    provider: "NVIDIA",
    category: "language",
    contextWindow: 4096,
    description: "On-device AI model for embedded robotics and automotive.",
  },
  {
    id: "fuyu-8b",
    name: "Fuyu 8B",
    provider: "NVIDIA",
    category: "vision",
    contextWindow: 4096,
    description: "Simplified vision-language architecture processing raw pixels directly.",
  },
  {
    id: "megatron-lm-22b",
    name: "Megatron-LM 22B",
    provider: "NVIDIA",
    category: "language",
    contextWindow: 4096,
    description: "Research foundation model trained via Megatron framework.",
  },

  // --- DeepSeek (10) ---
  {
    id: "deepseek-v3",
    name: "DeepSeek V3",
    provider: "DeepSeek",
    category: "language",
    contextWindow: 128000,
    description: "671B parameter Mixture-of-Experts model trained at fraction of traditional cost.",
  },
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    provider: "DeepSeek",
    category: "language",
    contextWindow: 128000,
    description: "Reasoning model using RL without supervised fine-tuning to rival o1.",
  },
  {
    id: "deepseek-r1-distill-qwen-32b",
    name: "DeepSeek R1 Distill Qwen 32B",
    provider: "DeepSeek",
    category: "language",
    contextWindow: 128000,
    description: "Reasoning distillate model based on Qwen architecture.",
  },
  {
    id: "deepseek-r1-distill-llama-70b",
    name: "DeepSeek R1 Distill Llama 70B",
    provider: "DeepSeek",
    category: "language",
    contextWindow: 128000,
    description: "Distilled open reasoning model built upon Llama 3.1 70B.",
  },
  {
    id: "deepseek-coder-v2",
    name: "DeepSeek Coder V2",
    provider: "DeepSeek",
    category: "code",
    contextWindow: 128000,
    description: "236B MoE code model matching top proprietary systems in software engineering.",
  },
  {
    id: "deepseek-coder-33b",
    name: "DeepSeek Coder 33B",
    provider: "DeepSeek",
    category: "code",
    contextWindow: 16384,
    description: "First-generation specialized programming model.",
  },
  {
    id: "deepseek-llm-67b",
    name: "DeepSeek LLM 67B",
    provider: "DeepSeek",
    category: "language",
    contextWindow: 4096,
    description: "Dense open weights foundation model.",
  },
  {
    id: "deepseek-vl-7b",
    name: "DeepSeek VL 7B",
    provider: "DeepSeek",
    category: "vision",
    contextWindow: 4096,
    description: "Open vision-language model for real-world visual grounding.",
  },
  {
    id: "deepseek-v2.5",
    name: "DeepSeek V2.5",
    provider: "DeepSeek",
    category: "code",
    contextWindow: 128000,
    description: "Unified model combining general reasoning and specialized coding.",
  },
  {
    id: "deepseek-math-7b",
    name: "DeepSeek Math 7B",
    provider: "DeepSeek",
    category: "language",
    contextWindow: 4096,
    description: "Mathematical reasoning model trained on DeepSeekMath Corpus.",
  },

  // --- Cohere (8) ---
  {
    id: "command-r-plus",
    name: "Command R+",
    provider: "Cohere",
    category: "language",
    contextWindow: 128000,
    description: "Enterprise model optimized for retrieval-augmented generation and tool use.",
  },
  {
    id: "command-r",
    name: "Command R",
    provider: "Cohere",
    category: "language",
    contextWindow: 128000,
    description: "Scalable RAG model for enterprise production workflows.",
  },
  {
    id: "command-light",
    name: "Command Light",
    provider: "Cohere",
    category: "language",
    contextWindow: 4096,
    description: "Fast low-latency model for simple classification and completion.",
  },
  {
    id: "embed-english-v3.0",
    name: "Embed English v3.0",
    provider: "Cohere",
    category: "embedding",
    contextWindow: 512,
    description: "Leading English semantic search embedding model.",
  },
  {
    id: "embed-multilingual-v3.0",
    name: "Embed Multilingual v3.0",
    provider: "Cohere",
    category: "embedding",
    contextWindow: 512,
    description: "Multilingual vector search model supporting 100+ languages.",
  },
  {
    id: "rerank-v3.5",
    name: "Rerank v3.5",
    provider: "Cohere",
    category: "embedding",
    contextWindow: 4096,
    description: "Advanced document reranking model for precision RAG pipelines.",
  },
  {
    id: "rerank-multilingual-v3.0",
    name: "Rerank Multilingual v3.0",
    provider: "Cohere",
    category: "embedding",
    contextWindow: 4096,
    description: "Cross-lingual search document relevance ranker.",
  },
  {
    id: "command-a",
    name: "Command A",
    provider: "Cohere",
    category: "code",
    contextWindow: 256000,
    description: "Agentic workflow model built for tool calling and API execution.",
  },

  // --- xAI (6) ---
  {
    id: "grok-3",
    name: "Grok 3",
    provider: "xAI",
    category: "language",
    contextWindow: 1000000,
    description: "Frontier supercomputing intelligence model trained on Colossus cluster.",
  },
  {
    id: "grok-2",
    name: "Grok 2",
    provider: "xAI",
    category: "language",
    contextWindow: 128000,
    description: "High-performance LLM with real-time web access.",
  },
  {
    id: "grok-2-vision",
    name: "Grok 2 Vision",
    provider: "xAI",
    category: "vision",
    contextWindow: 128000,
    description: "Multimodal Grok model with document and visual reasoning capabilities.",
  },
  {
    id: "grok-1.5",
    name: "Grok 1.5",
    provider: "xAI",
    category: "language",
    contextWindow: 128000,
    description: "Improved reasoning model with extended context window.",
  },
  {
    id: "grok-1.5-vision",
    name: "Grok 1.5 Vision",
    provider: "xAI",
    category: "vision",
    contextWindow: 128000,
    description: "First multimodal variant of xAI's foundation model.",
  },
  {
    id: "grok-1",
    name: "Grok 1",
    provider: "xAI",
    category: "language",
    contextWindow: 8192,
    description: "314B open-weights base language model.",
  },

  // --- Perplexity (6) ---
  {
    id: "sonar-pro",
    name: "Sonar Pro",
    provider: "Perplexity",
    category: "language",
    contextWindow: 200000,
    description: "Advanced search grounding model with live web synthesis.",
  },
  {
    id: "sonar",
    name: "Sonar",
    provider: "Perplexity",
    category: "language",
    contextWindow: 128000,
    description: "Fast search answer engine model.",
  },
  {
    id: "sonar-reasoning",
    name: "Sonar Reasoning",
    provider: "Perplexity",
    category: "language",
    contextWindow: 128000,
    description: "Search-augmented reasoning model with explicit chain of thought.",
  },
  {
    id: "sonar-reasoning-pro",
    name: "Sonar Reasoning Pro",
    provider: "Perplexity",
    category: "language",
    contextWindow: 128000,
    description: "Top-tier search and multi-step reasoning model.",
  },
  {
    id: "pplx-70b-online",
    name: "PPLX 70B Online",
    provider: "Perplexity",
    category: "language",
    contextWindow: 4096,
    description: "Legacy 70B web-connected answer engine model.",
  },
  {
    id: "pplx-7b-online",
    name: "PPLX 7B Online",
    provider: "Perplexity",
    category: "language",
    contextWindow: 4096,
    description: "Legacy 7B real-time search LLM.",
  },

  // --- Stability AI (8) ---
  {
    id: "stable-diffusion-3.5-large",
    name: "SD 3.5 Large",
    provider: "Stability AI",
    category: "image",
    description: "8B parameter MMDiT image generation flagship model.",
  },
  {
    id: "stable-diffusion-3.5-medium",
    name: "SD 3.5 Medium",
    provider: "Stability AI",
    category: "image",
    description: "2.5B parameter image generation model optimized for consumer GPUs.",
  },
  {
    id: "stable-diffusion-3-medium",
    name: "SD 3 Medium",
    provider: "Stability AI",
    category: "image",
    description: "Multimodal Diffusion Transformer architecture for realistic image synthesis.",
  },
  {
    id: "sd-xl-turbo",
    name: "SDXL Turbo",
    provider: "Stability AI",
    category: "image",
    description: "Real-time single-step adversarial diffusion model.",
  },
  {
    id: "sd-xl-1.0",
    name: "SDXL 1.0",
    provider: "Stability AI",
    category: "image",
    description: "High-resolution 1024x1024 open image model.",
  },
  {
    id: "stable-video-diffusion",
    name: "Stable Video Diffusion",
    provider: "Stability AI",
    category: "vision",
    description: "Generative video model producing short motion clips.",
  },
  {
    id: "stable-cascade",
    name: "Stable Cascade",
    provider: "Stability AI",
    category: "image",
    description: "Würstchen architecture highly compressed text-to-image model.",
  },
  {
    id: "stable-audio-2",
    name: "Stable Audio 2.0",
    provider: "Stability AI",
    category: "language",
    description: "High-fidelity full track audio and music generation model.",
  },

  // --- HuggingFace / Open Community (14) ---
  {
    id: "zephyr-7b-beta",
    name: "Zephyr 7B Beta",
    provider: "HuggingFace",
    category: "language",
    contextWindow: 8192,
    description: "Direct Preference Optimization fine-tune of Mistral 7B.",
  },
  {
    id: "falcon-180b",
    name: "Falcon 180B",
    provider: "TII",
    category: "language",
    contextWindow: 4096,
    description: "180B parameter open foundation model built by TII.",
  },
  {
    id: "falcon-40b",
    name: "Falcon 40B",
    provider: "TII",
    category: "language",
    contextWindow: 2048,
    description: "High-performance open weights model from Technology Innovation Institute.",
  },
  {
    id: "falcon-7b",
    name: "Falcon 7B",
    provider: "TII",
    category: "language",
    contextWindow: 2048,
    description: "Compact open model for lightweight text processing.",
  },
  {
    id: "starcoder-2-15b",
    name: "StarCoder 2 15B",
    provider: "HuggingFace",
    category: "code",
    contextWindow: 16384,
    description: "Code generation model trained on BigCode dataset.",
  },
  {
    id: "wizardlm-2-8x22b",
    name: "WizardLM-2 8x22B",
    provider: "Microsoft",
    category: "language",
    contextWindow: 65536,
    description: "State-of-the-art synthetic data fine-tuned MoE model.",
  },
  {
    id: "openchat-3.5",
    name: "OpenChat 3.5",
    provider: "OpenChat",
    category: "language",
    contextWindow: 8192,
    description: "C-RLFT aligned model competing with ChatGPT-3.5.",
  },
  {
    id: "vicuna-33b",
    name: "Vicuna 33B",
    provider: "LMSYS",
    category: "language",
    contextWindow: 4096,
    description: "LLaMA-tuned chatbot model evaluated by LMSYS.",
  },
  {
    id: "solar-10.7b",
    name: "SOLAR 10.7B",
    provider: "Upstage",
    category: "language",
    contextWindow: 4096,
    description: "Depth-Up-Scaled fine-tuned open language model.",
  },
  {
    id: "phi-3.5-mini",
    name: "Phi-3.5 Mini",
    provider: "Microsoft",
    category: "language",
    contextWindow: 128000,
    description: "Small language model with strong reasoning capabilities.",
  },
  {
    id: "phi-3.5-vision",
    name: "Phi-3.5 Vision",
    provider: "Microsoft",
    category: "vision",
    contextWindow: 128000,
    description: "Multimodal small language model for charts and images.",
  },
  {
    id: "hermes-3-llama-70b",
    name: "Hermes 3 Llama 70B",
    provider: "Nous Research",
    category: "language",
    contextWindow: 128000,
    description: "Frontier open-weights agentic model fine-tuned by Nous Research.",
  },
  {
    id: "yi-1.5-34b",
    name: "Yi 1.5 34B",
    provider: "01.AI",
    category: "language",
    contextWindow: 4096,
    description: "Open source bilingual foundation model by Kai-Fu Lee's team.",
  },
  {
    id: "deepseek-moe-16b",
    name: "DeepSeek MoE 16B",
    provider: "DeepSeek",
    category: "language",
    contextWindow: 4096,
    description: "Early sparse architecture model testing fine-grained expert activation.",
  },

  // --- Inflection AI (3) ---
  {
    id: "inflection-2.5",
    name: "Inflection 2.5",
    provider: "Inflection",
    category: "language",
    contextWindow: 32768,
    description: "Empathetic conversational model powering Pi chatbot.",
  },
  {
    id: "inflection-2",
    name: "Inflection 2",
    provider: "Inflection",
    category: "language",
    contextWindow: 8192,
    description: "High-efficiency base model for conversational intelligence.",
  },
  {
    id: "inflection-1",
    name: "Inflection 1",
    provider: "Inflection",
    category: "language",
    contextWindow: 4096,
    description: "Initial personal AI foundation model.",
  },

  // --- Image / Audio & Specialized (23) ---
  {
    id: "flux-1-dev",
    name: "FLUX.1 [dev]",
    provider: "Black Forest Labs",
    category: "image",
    description: "Open-weight guidance-distilled 12B parameter image generation model.",
  },
  {
    id: "flux-1-schnell",
    name: "FLUX.1 [schnell]",
    provider: "Black Forest Labs",
    category: "image",
    description: "Ultra-fast step-distilled open image generation model.",
  },
  {
    id: "flux-1-pro",
    name: "FLUX.1 [pro]",
    provider: "Black Forest Labs",
    category: "image",
    description: "State-of-the-art commercial image generation model.",
  },
  {
    id: "flux-1.1-pro",
    name: "FLUX.1.1 [pro]",
    provider: "Black Forest Labs",
    category: "image",
    description: "Next-gen ultra-high-definition image model with accelerated generation.",
  },
  {
    id: "ideogram-v2",
    name: "Ideogram v2",
    provider: "Ideogram",
    category: "image",
    description:
      "Industry leader for graphic design, typography, and crisp text rendering in images.",
  },
  {
    id: "recraft-v3",
    name: "Recraft v3",
    provider: "Recraft",
    category: "image",
    description: "Vector and raster generative design model for UI/UX assets.",
  },
  {
    id: "midjourney-v6.1",
    name: "Midjourney v6.1",
    provider: "Midjourney",
    category: "image",
    description: "Benchmark photorealistic image generation model.",
  },
  {
    id: "midjourney-v6",
    name: "Midjourney v6",
    provider: "Midjourney",
    category: "image",
    description: "Coherent fine-grained photorealistic synthesis engine.",
  },
  {
    id: "eleven-multilingual-v2",
    name: "Eleven Multilingual v2",
    provider: "ElevenLabs",
    category: "language",
    description: "Natural sounding voice clone and text-to-speech synthesis model.",
  },
  {
    id: "eleven-turbo-v2.5",
    name: "Eleven Turbo v2.5",
    provider: "ElevenLabs",
    category: "language",
    description: "Low-latency streaming voice model for conversational agents.",
  },
  {
    id: "suno-v4",
    name: "Suno v4",
    provider: "Suno",
    category: "language",
    description: "Generative audio model synthesizing complete songs with vocals.",
  },
  {
    id: "udio-v1.5",
    name: "Udio v1.5",
    provider: "Udio",
    category: "language",
    description: "High-fidelity music generation model with multi-track stems.",
  },
  {
    id: "runway-gen-3-alpha",
    name: "Runway Gen-3 Alpha",
    provider: "Runway",
    category: "vision",
    description: "High-fidelity text-to-video and image-to-video diffusion model.",
  },
  {
    id: "luma-dream-machine",
    name: "Dream Machine",
    provider: "Luma AI",
    category: "vision",
    description: "Fast high-definition video generation model.",
  },
  {
    id: "kling-1.5",
    name: "Kling 1.5",
    provider: "Kuaishou",
    category: "vision",
    description: "Photorealistic 1080p video generation model.",
  },
  {
    id: "pika-2.0",
    name: "Pika 2.0",
    provider: "Pika",
    category: "vision",
    description: "AI video engine with specialized camera controls and object effects.",
  },
  {
    id: "bge-large-en-v1.5",
    name: "BGE Large EN v1.5",
    provider: "BAAI",
    category: "embedding",
    contextWindow: 512,
    description: "Top performing open-source embedding model on MTEB leaderboard.",
  },
  {
    id: "bge-m3",
    name: "BGE M3",
    provider: "BAAI",
    category: "embedding",
    contextWindow: 8192,
    description: "Multi-linguality, Multi-granularity, and Multi-functionality embedding model.",
  },
  {
    id: "gte-large-en-v1.5",
    name: "GTE Large EN",
    provider: "Alibaba",
    category: "embedding",
    contextWindow: 8192,
    description: "General Text Embedding model for retrieval search.",
  },
  {
    id: "jina-embeddings-v3",
    name: "Jina Embeddings v3",
    provider: "Jina AI",
    category: "embedding",
    contextWindow: 8192,
    description: "Multilingual 8192 context embedding model.",
  },
  {
    id: "whisper-large-v3-turbo",
    name: "Whisper Large v3 Turbo",
    provider: "OpenAI",
    category: "language",
    description: "Pruned version of Whisper Large v3 providing 8x faster transcription.",
  },
  {
    id: "bark",
    name: "Suno Bark",
    provider: "Suno",
    category: "language",
    description: "Transformer-based text-to-audio model capable of expressive speech and music.",
  },
  {
    id: "cosyvoice-300m",
    name: "CosyVoice 300M",
    provider: "Alibaba",
    category: "language",
    description: "Multi-lingual voice generation and zero-shot voice cloning model.",
  },
];
