import "server-only";

export const RATE_LIMITS = {
  global_incident_burst_guard: { max: 10, window: "1 m" },
  coordinated_incident_burst_guard: { max: 2, window: "10 m" },
  incident_submission: { max: 5, window: "1 h" },
  incident_submission_fp: { max: 5, window: "1 h" },
  suggestion_submission: { max: 10, window: "1 d" },
  contact_submission: { max: 5, window: "1 h" },
  takedown_submission: { max: 3, window: "1 d" },
  auth_signin: { max: 10, window: "15 m" },
  auth_magiclink: { max: 5, window: "15 m" },
  search_query: { max: 30, window: "1 m" },
  export_request: { max: 5, window: "1 h" },
  api_general: { max: 100, window: "1 m" },
  api_free: { max: 5, window: "1 m" },
  api_developer: { max: 30, window: "1 m" },
  api_enterprise: { max: 100, window: "1 m" },
  model_review: { max: 3, window: "1 d" },
  model_feature_request: { max: 5, window: "1 d" },
  dilemma_vote: { max: 3, window: "1 d" },
  incident_vote: { max: 20, window: "1 m" },
  whistleblower_submission: { max: 3, window: "1 d" },
  incident_comment: { max: 5, window: "15 m" },
  incident_affected: { max: 1, window: "1 d" },
  onboarding: { max: 3, window: "1 h" },
  expert_application: { max: 2, window: "1 d" },
  investor_application: { max: 2, window: "1 d" },
  provider_response: { max: 5, window: "1 h" },
  email_notification: { max: 10, window: "1 h" },
  vertex_scout: { max: 20, window: "1 m" },
  unsubscribe_attempt: { max: 5, window: "1 h" },
} as const satisfies Record<string, { max: number; window: string }>;
