"use client";

import React from "react";
import { Check, X, Megaphone, ShareNetwork, Video } from "@phosphor-icons/react";

export function SocialClient() {
  // Mock drafts for the UI until DB is populated
  const drafts = [
    {
      id: "1",
      platform: "LinkedIn",
      content: "Excited to announce our new ALPAR AI transparency features... #AI #Trust",
      media_url: "https://example.com/video1.mp4",
      status: "draft",
      created_at: "2026-07-16T10:00:00Z",
    },
  ];

  return (
    <div className="space-y-6">
      {/* Platform Connections */}
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <div className="bg-bg-secondary border-border-subtle flex items-center justify-between rounded-xl border p-6">
          <div className="flex items-center gap-4">
            <div className="rounded-lg border border-blue-500/20 bg-blue-500/10 p-3">
              <ShareNetwork className="h-6 w-6 text-blue-400" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">LinkedIn Company Page</h3>
              <p className="text-fg-muted text-sm">Status: Disconnected</p>
            </div>
          </div>
          <button className="bg-brand-500 hover:bg-brand-600 rounded-md px-4 py-2 text-sm font-semibold text-white transition-colors">
            Connect
          </button>
        </div>

        <div className="bg-bg-secondary border-border-subtle flex items-center justify-between rounded-xl border p-6">
          <div className="flex items-center gap-4">
            <div className="rounded-lg border border-sky-500/20 bg-sky-500/10 p-3">
              <ShareNetwork className="h-6 w-6 text-sky-400" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-white">X (Twitter)</h3>
              <p className="text-fg-muted text-sm">Status: Disconnected</p>
            </div>
          </div>
          <button className="bg-brand-500 hover:bg-brand-600 rounded-md px-4 py-2 text-sm font-semibold text-white transition-colors">
            Connect
          </button>
        </div>
      </div>

      {/* Human in the loop queue */}
      <div className="mt-8">
        <h2 className="mb-4 flex items-center gap-2 text-xl font-bold text-white">
          <Megaphone className="text-brand-400 h-5 w-5" />
          Approval Queue (Human in the Loop)
        </h2>

        {drafts.length === 0 ? (
          <div className="bg-bg-secondary border-border-subtle rounded-xl border p-12 text-center">
            <p className="text-fg-muted">
              No pending drafts. Spark will generate new content soon.
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {drafts.map((draft) => (
              <div
                key={draft.id}
                className="bg-bg-secondary border-border-subtle overflow-hidden rounded-xl border"
              >
                <div className="border-border-subtle bg-bg-tertiary flex items-center justify-between border-b p-4">
                  <div className="flex items-center gap-2">
                    <span className="rounded border border-blue-500/20 bg-blue-500/10 px-2 py-1 text-xs font-bold tracking-wider text-blue-400 uppercase">
                      {draft.platform}
                    </span>
                    <span className="text-fg-muted text-xs">Generated by Spark</span>
                  </div>
                  <span className="text-fg-muted text-xs">
                    {new Date(draft.created_at).toLocaleString()}
                  </span>
                </div>

                <div className="flex flex-col gap-6 p-6 md:flex-row">
                  <div className="flex-1">
                    <p className="whitespace-pre-wrap text-white">{draft.content}</p>
                  </div>
                  <div className="w-full shrink-0 md:w-64">
                    <div className="border-border-subtle relative flex aspect-video items-center justify-center overflow-hidden rounded-lg border bg-black">
                      <Video className="text-fg-muted h-8 w-8" />
                      <div className="absolute right-2 bottom-2 left-2 rounded bg-black/50 py-1 text-center text-xs text-white backdrop-blur-sm">
                        Preview (Placeholder)
                      </div>
                    </div>
                  </div>
                </div>

                <div className="border-border-subtle bg-bg-tertiary/50 flex items-center justify-end gap-3 border-t p-4">
                  <button className="flex items-center gap-2 rounded-md border border-red-500/20 bg-red-500/10 px-4 py-2 text-sm font-semibold text-red-500 transition-colors hover:bg-red-500/20">
                    <X className="h-4 w-4" />
                    Reject
                  </button>
                  <button className="flex items-center gap-2 rounded-md bg-emerald-500 px-6 py-2 text-sm font-semibold text-white shadow-[0_0_15px_rgba(16,185,129,0.3)] transition-all hover:scale-105 hover:bg-emerald-600">
                    <Check className="h-4 w-4" />
                    Approve & Publish
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
