"use server";

import { createAdminClient } from "@/lib/supabase/admin";
import { requireModerator } from "@/lib/auth/session";
const MIN_MONTHLY_THRESHOLD = 30;

export interface KpiMetric {
  label: string;
  thisMonth: number;
  lastMonth: number;
  momGrowthPct: number | null;
  status: "ok" | "insufficient_data";
}

export interface StartupHealthResult {
  kpis: KpiMetric[];
  showPercentages: boolean;
  measuredAt: string;
}

function momGrowth(current: number, previous: number): number | null {
  if (previous === 0) return current > 0 ? 100 : null;
  if (previous === 0 && current === 0) return null; // no signal
  return Math.round(((current - previous) / previous) * 100);
}

export async function getStartupHealth(): Promise<StartupHealthResult | null> {
  const user = await requireModerator();
  if (!user) return null;

  const db = createAdminClient();

  // We cast to suppress TS error since startup_health_kpis is not in autogenerated types yet
  const { data: rawData, error } = await db.rpc("startup_health_kpis" as never);
  if (error || !rawData) return null;

  const data = rawData as {
    users: { this_month: number; last_month: number };
    incidents: { this_month: number; last_month: number };
    subscribers: { this_month: number; last_month: number };
  };

  const usersThis = data.users.this_month;
  const usersLast = data.users.last_month;
  const incidentsThis = data.incidents.this_month;
  const incidentsLast = data.incidents.last_month;
  const newsletterThis = data.subscribers.this_month;
  const newsletterLast = data.subscribers.last_month;

  const rawKpis: KpiMetric[] = [
    {
      label: "New Users",
      thisMonth: usersThis,
      lastMonth: usersLast,
      momGrowthPct: usersThis >= MIN_MONTHLY_THRESHOLD ? momGrowth(usersThis, usersLast) : null,
      status: usersThis >= MIN_MONTHLY_THRESHOLD ? "ok" : "insufficient_data",
    },
    {
      label: "Incidents Filed",
      thisMonth: incidentsThis,
      lastMonth: incidentsLast,
      momGrowthPct:
        incidentsThis >= MIN_MONTHLY_THRESHOLD ? momGrowth(incidentsThis, incidentsLast) : null,
      status: incidentsThis >= MIN_MONTHLY_THRESHOLD ? "ok" : "insufficient_data",
    },
    {
      label: "Newsletter Subscribers",
      thisMonth: newsletterThis,
      lastMonth: newsletterLast,
      momGrowthPct:
        newsletterThis >= MIN_MONTHLY_THRESHOLD ? momGrowth(newsletterThis, newsletterLast) : null,
      status: newsletterThis >= MIN_MONTHLY_THRESHOLD ? "ok" : "insufficient_data",
    },
  ];

  const passing = rawKpis.filter((k) => k.status === "ok").length;

  return {
    kpis: rawKpis,
    showPercentages: passing >= 2,
    measuredAt: new Date().toISOString(),
  };
}
