import type { IntegrationService } from "./types";

export const INTEGRATION_SERVICES: IntegrationService[] = [
  {
    id: "github",
    name: "GitHub",
    category: "version-control",
    description: "Source code hosting, version control, and PR management",
    logo: "github",
    brandColor: "#181717",
    envVars: ["GITHUB_PERSONAL_ACCESS_TOKEN"],
    costKey: "github",
    healthKey: "github",
    alternatives: ["gitlab", "bitbucket", "gitea"],
    url: "https://github.com/quantummatrixcore-lab/Alparai.com",
    docsUrl: "https://docs.github.com",
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "version-control",
    description: "DevOps platform with built-in CI/CD and container registry",
    logo: "gitlab",
    brandColor: "#FC6D26",
    envVars: [],
    alternatives: ["github", "bitbucket", "gitea"],
    url: "https://gitlab.com",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    category: "version-control",
    description: "Git hosting with Jira integration and Pipelines CI/CD",
    logo: "bitbucket",
    brandColor: "#0052CC",
    envVars: [],
    alternatives: ["github", "gitlab", "gitea"],
    url: "https://bitbucket.org",
  },
  {
    id: "gitea",
    name: "Gitea",
    category: "version-control",
    description: "Lightweight self-hosted Git service",
    logo: "gitea",
    brandColor: "#609926",
    envVars: [],
    alternatives: ["github", "gitlab", "bitbucket"],
    url: "https://gitea.io",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "hosting",
    description: "Frontend hosting, serverless functions, and edge infrastructure",
    logo: "vercel",
    brandColor: "#000000",
    envVars: ["VERCEL_TOKEN", "VERCEL_OIDC_TOKEN"],
    costKey: "vercel",
    healthKey: "vercel",
    alternatives: ["netlify", "cloudflare-pages", "railway"],
    url: "https://vercel.com/alpar-ai",
    docsUrl: "https://vercel.com/docs",
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "hosting",
    description: "Web hosting with serverless functions and form handling",
    logo: "netlify",
    brandColor: "#00C7B7",
    envVars: [],
    alternatives: ["vercel", "cloudflare-pages", "railway"],
    url: "https://netlify.com",
  },
  {
    id: "cloudflare-pages",
    name: "Cloudflare Pages",
    category: "hosting",
    description: "Edge-rendered hosting on Cloudflare's global network",
    logo: "cloudflare",
    brandColor: "#F38020",
    envVars: [],
    alternatives: ["vercel", "netlify", "railway"],
    url: "https://pages.cloudflare.com",
  },
  {
    id: "railway",
    name: "Railway",
    category: "hosting",
    description: "Simple full-stack hosting with integrated databases",
    logo: "railway",
    brandColor: "#0B0D0E",
    envVars: [],
    alternatives: ["vercel", "netlify", "cloudflare-pages"],
    url: "https://railway.app",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "database",
    description: "PostgreSQL database, auth, storage, and realtime subscriptions",
    logo: "supabase",
    brandColor: "#3ECF8E",
    envVars: [
      "NEXT_PUBLIC_SUPABASE_URL",
      "NEXT_PUBLIC_SUPABASE_ANON_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
    ],
    costKey: "supabase",
    healthKey: "supabase",
    alternatives: ["neon", "turso", "planetscale"],
    url: "https://supabase.com",
    docsUrl: "https://supabase.com/docs",
  },
  {
    id: "neon",
    name: "Neon",
    category: "database",
    description: "Serverless PostgreSQL with branching and auto-scale",
    logo: "neon",
    brandColor: "#00E599",
    envVars: [],
    alternatives: ["supabase", "turso", "planetscale"],
    url: "https://neon.tech",
  },
  {
    id: "turso",
    name: "Turso",
    category: "database",
    description: "Edge SQLite database with libsql and replication",
    logo: "turso",
    brandColor: "#4FF8D2",
    envVars: [],
    alternatives: ["supabase", "neon", "planetscale"],
    url: "https://turso.tech",
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    category: "database",
    description: "MySQL-compatible serverless database with branching",
    logo: "planetscale",
    brandColor: "#000000",
    envVars: [],
    alternatives: ["supabase", "neon", "turso"],
    url: "https://planetscale.com",
  },
  {
    id: "upstash",
    name: "Upstash Redis",
    category: "cache",
    description: "Serverless Redis for caching, rate limiting, and realtime",
    logo: "upstash",
    brandColor: "#00E5FF",
    envVars: ["UPSTASH_REDIS_REST_URL", "UPSTASH_REDIS_REST_TOKEN"],
    costKey: "upstash",
    healthKey: "redis",
    alternatives: ["redis-cloud", "dragonfly", "keydb"],
    url: "https://upstash.com",
    docsUrl: "https://upstash.com/docs",
  },
  {
    id: "redis-cloud",
    name: "Redis Cloud",
    category: "cache",
    description: "Fully managed Redis with enterprise-grade reliability",
    logo: "redis",
    brandColor: "#DC382D",
    envVars: [],
    alternatives: ["upstash", "dragonfly", "keydb"],
    url: "https://redis.com",
  },
  {
    id: "dragonfly",
    name: "Dragonfly",
    category: "cache",
    description: "High-performance in-memory data store (Redis/Memcached compatible)",
    logo: "dragonfly",
    brandColor: "#32CD32",
    envVars: [],
    alternatives: ["upstash", "redis-cloud", "keydb"],
    url: "https://dragonflydb.io",
  },
  {
    id: "keydb",
    name: "KeyDB",
    category: "cache",
    description: "Multi-threaded Redis-compatible database",
    logo: "keydb",
    brandColor: "#A31F34",
    envVars: [],
    alternatives: ["upstash", "redis-cloud", "dragonfly"],
    url: "https://keydb.dev",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "cdn-security",
    description: "CDN, DDoS protection, Turnstile bot detection, and DNS",
    logo: "cloudflare",
    brandColor: "#F38020",
    envVars: ["NEXT_PUBLIC_TURNSTILE_SITE_KEY", "TURNSTILE_SECRET_KEY"],
    costKey: "cloudflare",
    healthKey: "cloudflare",
    alternatives: ["recaptcha", "hcaptcha", "friendly-captcha"],
    url: "https://dash.cloudflare.com",
    docsUrl: "https://developers.cloudflare.com",
  },
  {
    id: "recaptcha",
    name: "Google reCAPTCHA",
    category: "cdn-security",
    description: "Google's bot detection service (v2/v3/Enterprise)",
    logo: "google",
    brandColor: "#4285F4",
    envVars: [],
    alternatives: ["cloudflare", "hcaptcha", "friendly-captcha"],
    url: "https://www.google.com/recaptcha",
  },
  {
    id: "hcaptcha",
    name: "hCaptcha",
    category: "cdn-security",
    description: "Privacy-focused CAPTCHA and bot detection service",
    logo: "hcaptcha",
    brandColor: "#3358FF",
    envVars: [],
    alternatives: ["cloudflare", "recaptcha", "friendly-captcha"],
    url: "https://www.hcaptcha.com",
  },
  {
    id: "friendly-captcha",
    name: "Friendly Captcha",
    category: "cdn-security",
    description: "Privacy-first bot protection, no user interaction needed",
    logo: "friendly-captcha",
    brandColor: "#6C5CE7",
    envVars: [],
    alternatives: ["cloudflare", "recaptcha", "hcaptcha"],
    url: "https://friendlycaptcha.com",
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "error-tracking",
    description: "Real-time error tracking, crash reporting, and performance monitoring",
    logo: "sentry",
    brandColor: "#FB4226",
    envVars: ["SENTRY_DSN", "NEXT_PUBLIC_SENTRY_DSN"],
    costKey: "sentry",
    healthKey: "sentry",
    alternatives: ["datadog", "grafana-faro", "highlight"],
    url: "https://sentry.io",
    docsUrl: "https://docs.sentry.io",
  },
  {
    id: "datadog",
    name: "Datadog",
    category: "error-tracking",
    description: "Full-stack observability, APM, logs, and infrastructure monitoring",
    logo: "datadog",
    brandColor: "#632CA6",
    envVars: [],
    alternatives: ["sentry", "grafana-faro", "highlight"],
    url: "https://datadoghq.com",
  },
  {
    id: "grafana-faro",
    name: "Grafana Faro",
    category: "error-tracking",
    description: "Open-source frontend observability and real user monitoring",
    logo: "grafana",
    brandColor: "#F46800",
    envVars: [],
    alternatives: ["sentry", "datadog", "highlight"],
    url: "https://grafana.com/oss/faro",
  },
  {
    id: "highlight",
    name: "Highlight",
    category: "error-tracking",
    description: "Open-source session replay and error monitoring",
    logo: "highlight",
    brandColor: "#F97316",
    envVars: [],
    alternatives: ["sentry", "datadog", "grafana-faro"],
    url: "https://highlight.io",
  },
  {
    id: "resend",
    name: "Resend",
    category: "email",
    description: "Email API for developers with high deliverability",
    logo: "resend",
    brandColor: "#000000",
    envVars: ["RESEND_API_KEY"],
    costKey: "resend",
    healthKey: "resend",
    alternatives: ["sendgrid", "mailgun", "postmark"],
    url: "https://resend.com",
    docsUrl: "https://resend.com/docs",
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    category: "email",
    description: "Twilio's email delivery service with broad integrations",
    logo: "sendgrid",
    brandColor: "#1A82E2",
    envVars: [],
    alternatives: ["resend", "mailgun", "postmark"],
    url: "https://sendgrid.com",
  },
  {
    id: "mailgun",
    name: "Mailgun",
    category: "email",
    description: "Email API for sending, receiving, and tracking emails",
    logo: "mailgun",
    brandColor: "#F06B66",
    envVars: [],
    alternatives: ["resend", "sendgrid", "postmark"],
    url: "https://mailgun.com",
  },
  {
    id: "postmark",
    name: "Postmark",
    category: "email",
    description: "Fast transactional email delivery with low latency",
    logo: "postmark",
    brandColor: "#FFE01B",
    envVars: [],
    alternatives: ["resend", "sendgrid", "mailgun"],
    url: "https://postmarkapp.com",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    description: "Payment processing, subscriptions, and billing infrastructure",
    logo: "stripe",
    brandColor: "#008CDD",
    envVars: ["STRIPE_SECRET_KEY", "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"],
    costKey: "stripe",
    healthKey: "stripe",
    alternatives: ["paddle", "lemon-squeezy", "chargebee"],
    url: "https://dashboard.stripe.com",
    docsUrl: "https://stripe.com/docs",
  },
  {
    id: "paddle",
    name: "Paddle",
    category: "payments",
    description: "Full-stack payment infrastructure with global tax compliance",
    logo: "paddle",
    brandColor: "#0066FF",
    envVars: [],
    alternatives: ["stripe", "lemon-squeezy", "chargebee"],
    url: "https://paddle.com",
  },
  {
    id: "lemon-squeezy",
    name: "Lemon Squeezy",
    category: "payments",
    description: "Payment platform for SaaS with built-in licensing",
    logo: "lemon-squeezy",
    brandColor: "#FFC233",
    envVars: [],
    alternatives: ["stripe", "paddle", "chargebee"],
    url: "https://lemonsqueezy.com",
  },
  {
    id: "chargebee",
    name: "Chargebee",
    category: "payments",
    description: "Subscription billing and revenue management platform",
    logo: "chargebee",
    brandColor: "#3B82F6",
    envVars: [],
    alternatives: ["stripe", "paddle", "lemon-squeezy"],
    url: "https://chargebee.com",
  },
  {
    id: "github-actions",
    name: "GitHub Actions",
    category: "ci-cd",
    description: "CI/CD pipelines, automated builds, and deployment workflows",
    logo: "github-actions",
    brandColor: "#2088FF",
    envVars: ["GITHUB_PERSONAL_ACCESS_TOKEN"],
    costKey: "github",
    healthKey: "github",
    alternatives: ["gitlab-ci", "circleci", "jenkins"],
    url: "https://github.com/quantummatrixcore-lab/Alparai.com/actions",
    docsUrl: "https://docs.github.com/actions",
  },
  {
    id: "gitlab-ci",
    name: "GitLab CI",
    category: "ci-cd",
    description: "Built-in CI/CD with auto DevOps and container scanning",
    logo: "gitlab",
    brandColor: "#FC6D26",
    envVars: [],
    alternatives: ["github-actions", "circleci", "jenkins"],
    url: "https://gitlab.com",
  },
  {
    id: "circleci",
    name: "CircleCI",
    category: "ci-cd",
    description: "Cloud-native CI/CD with fast parallel execution",
    logo: "circleci",
    brandColor: "#343434",
    envVars: [],
    alternatives: ["github-actions", "gitlab-ci", "jenkins"],
    url: "https://circleci.com",
  },
  {
    id: "jenkins",
    name: "Jenkins",
    category: "ci-cd",
    description: "Self-hosted automation server with extensive plugin ecosystem",
    logo: "jenkins",
    brandColor: "#D24939",
    envVars: [],
    alternatives: ["github-actions", "gitlab-ci", "circleci"],
    url: "https://jenkins.io",
  },
  {
    id: "playwright",
    name: "Playwright",
    category: "testing",
    description: "Cross-browser E2E test automation by Microsoft",
    logo: "playwright",
    brandColor: "#45BA4B",
    envVars: [],
    costKey: "playwright",
    healthKey: "playwright",
    alternatives: ["cypress", "selenium", "puppeteer"],
    url: "https://playwright.dev",
    docsUrl: "https://playwright.dev/docs",
  },
  {
    id: "cypress",
    name: "Cypress",
    category: "testing",
    description: "Developer-friendly E2E testing with real-time reload",
    logo: "cypress",
    brandColor: "#69D3A7",
    envVars: [],
    alternatives: ["playwright", "selenium", "puppeteer"],
    url: "https://cypress.io",
  },
  {
    id: "selenium",
    name: "Selenium",
    category: "testing",
    description: "Browser automation framework supporting multiple languages",
    logo: "selenium",
    brandColor: "#43B02A",
    envVars: [],
    alternatives: ["playwright", "cypress", "puppeteer"],
    url: "https://selenium.dev",
  },
  {
    id: "puppeteer",
    name: "Puppeteer",
    category: "testing",
    description: "Browser automation by Google Chrome team (JavaScript)",
    logo: "puppeteer",
    brandColor: "#40B5A4",
    envVars: [],
    alternatives: ["playwright", "cypress", "selenium"],
    url: "https://pptr.dev",
  },
  {
    id: "husky",
    name: "Husky",
    category: "code-quality",
    description: "Git hooks automation for linting and testing pre-commit",
    logo: "husky",
    brandColor: "#000000",
    envVars: [],
    alternatives: ["lefthook", "pre-commit"],
    url: "https://typicode.github.io/husky",
  },
  {
    id: "lefthook",
    name: "Lefthook",
    category: "code-quality",
    description: "Fast, parallel Git hooks manager (Go-based)",
    logo: "lefthook",
    brandColor: "#FF1E56",
    envVars: [],
    alternatives: ["husky", "pre-commit"],
    url: "https://lefthook.dev",
  },
  {
    id: "pre-commit",
    name: "pre-commit",
    category: "code-quality",
    description: "Multi-language pre-commit hook framework (Python)",
    logo: "pre-commit",
    brandColor: "#F8B424",
    envVars: [],
    alternatives: ["husky", "lefthook"],
    url: "https://pre-commit.com",
  },
  {
    id: "google-oauth",
    name: "Google OAuth",
    category: "auth",
    description: "Google Sign-In for authentication and identity verification",
    logo: "google",
    brandColor: "#4285F4",
    envVars: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    alternatives: ["github-oauth", "auth0", "clerk"],
    url: "https://console.cloud.google.com",
    docsUrl: "https://developers.google.com/identity",
  },
  {
    id: "github-oauth",
    name: "GitHub OAuth",
    category: "auth",
    description: "GitHub-based authentication for developers",
    logo: "github",
    brandColor: "#181717",
    envVars: [],
    alternatives: ["google-oauth", "auth0", "clerk"],
    url: "https://github.com/settings/developers",
  },
  {
    id: "auth0",
    name: "Auth0",
    category: "auth",
    description: "Universal identity platform by Okta",
    logo: "auth0",
    brandColor: "#EB5424",
    envVars: [],
    alternatives: ["google-oauth", "github-oauth", "clerk"],
    url: "https://auth0.com",
  },
  {
    id: "clerk",
    name: "Clerk",
    category: "auth",
    description: "Modern user management and authentication platform",
    logo: "clerk",
    brandColor: "#6C47FF",
    envVars: [],
    alternatives: ["google-oauth", "github-oauth", "auth0"],
    url: "https://clerk.com",
  },
  {
    id: "vercel-analytics",
    name: "Vercel Analytics",
    category: "analytics",
    description: "Web analytics with privacy-friendly page view tracking",
    logo: "vercel",
    brandColor: "#000000",
    envVars: [],
    costKey: "vercel",
    healthKey: "vercel",
    alternatives: ["plausible", "umami", "fathom"],
    url: "https://vercel.com/alpar-ai/analytics",
    docsUrl: "https://vercel.com/docs/analytics",
  },
  {
    id: "plausible",
    name: "Plausible",
    category: "analytics",
    description: "Simple, privacy-friendly, open-source web analytics",
    logo: "plausible",
    brandColor: "#5850EC",
    envVars: [],
    alternatives: ["vercel-analytics", "umami", "fathom"],
    url: "https://plausible.io",
  },
  {
    id: "umami",
    name: "Umami",
    category: "analytics",
    description: "Self-hosted web analytics with GDPR compliance",
    logo: "umami",
    brandColor: "#000000",
    envVars: [],
    alternatives: ["vercel-analytics", "plausible", "fathom"],
    url: "https://umami.is",
  },
  {
    id: "fathom",
    name: "Fathom",
    category: "analytics",
    description: "Simple, privacy-focused website analytics",
    logo: "fathom",
    brandColor: "#9189FF",
    envVars: [],
    alternatives: ["vercel-analytics", "plausible", "umami"],
    url: "https://usefathom.com",
  },
  {
    id: "fingerprintjs",
    name: "FingerprintJS",
    category: "bot-detection",
    description: "Browser fingerprinting and fraud detection",
    logo: "fingerprintjs",
    brandColor: "#5C3EF0",
    envVars: ["NEXT_PUBLIC_FPJS_PUBLIC_KEY"],
    costKey: "fingerprintjs",
    alternatives: ["fingerprint-pro", "incognia"],
    url: "https://fingerprint.com",
    docsUrl: "https://dev.fingerprint.com",
  },
  {
    id: "fingerprint-pro",
    name: "Fingerprint Pro",
    category: "bot-detection",
    description: "Enterprise-grade browser fingerprinting with 99.5% accuracy",
    logo: "fingerprintjs",
    brandColor: "#5C3EF0",
    envVars: [],
    alternatives: ["fingerprintjs", "incognia"],
    url: "https://fingerprint.com",
  },
  {
    id: "incognia",
    name: "Incognia",
    category: "bot-detection",
    description: "Location-based fraud prevention and identity verification",
    logo: "incognia",
    brandColor: "#1E3A8A",
    envVars: [],
    alternatives: ["fingerprintjs", "fingerprint-pro"],
    url: "https://incognia.com",
  },
  {
    id: "vault",
    name: "AES-256-GCM Vault",
    category: "vault",
    description: "Self-managed encryption vault with AES-256-GCM master key",
    logo: "vault",
    brandColor: "#FFD54F",
    envVars: ["VAULT_MASTER_KEY"],
    alternatives: ["hashicorp-vault", "doppler", "op-cli"],
    url: "",
    docsUrl: "",
  },
  {
    id: "hashicorp-vault",
    name: "HashiCorp Vault",
    category: "vault",
    description: "Enterprise secrets management and encryption as a service",
    logo: "hashicorp",
    brandColor: "#000000",
    envVars: [],
    alternatives: ["vault", "doppler", "op-cli"],
    url: "https://vaultproject.io",
  },
  {
    id: "doppler",
    name: "Doppler",
    category: "vault",
    description: "Cloud-native secrets management with sync integrations",
    logo: "doppler",
    brandColor: "#00AEED",
    envVars: [],
    alternatives: ["vault", "hashicorp-vault", "op-cli"],
    url: "https://doppler.com",
  },
  {
    id: "op-cli",
    name: "1Password CLI",
    category: "vault",
    description: "Developer secrets automation via 1Password CLI",
    logo: "onepassword",
    brandColor: "#1A2B3C",
    envVars: [],
    alternatives: ["vault", "hashicorp-vault", "doppler"],
    url: "https://developer.1password.com",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "ai-models",
    description: "Unified API gateway for open and proprietary AI models",
    logo: "openrouter",
    brandColor: "#6366F1",
    envVars: ["OPENROUTER_API_KEY"],
    costKey: "openrouter",
    healthKey: "openrouter",
    alternatives: ["anthropic", "openai", "gemini"],
    url: "https://openrouter.ai",
    docsUrl: "https://openrouter.ai/docs",
  },
  {
    id: "anthropic",
    name: "Anthropic Claude",
    category: "ai-models",
    description: "Claude 3.5 Sonnet / Opus API for reasoning and coding",
    logo: "anthropic",
    brandColor: "#D97706",
    envVars: ["ANTHROPIC_API_KEY"],
    costKey: "anthropic",
    healthKey: "anthropic",
    alternatives: ["openrouter", "openai", "gemini"],
    url: "https://console.anthropic.com",
    docsUrl: "https://docs.anthropic.com",
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "ai-models",
    description: "GPT-4o, o1, and Embeddings API provider",
    logo: "openai",
    brandColor: "#10A37F",
    envVars: ["OPENAI_API_KEY"],
    costKey: "openai",
    healthKey: "openai",
    alternatives: ["openrouter", "anthropic", "gemini"],
    url: "https://platform.openai.com",
    docsUrl: "https://platform.openai.com/docs",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    category: "ai-models",
    description: "Google AI Studio & Vertex AI Gemini API",
    logo: "google",
    brandColor: "#4285F4",
    envVars: ["GEMINI_API_KEY", "GOOGLE_API_KEY"],
    costKey: "gemini",
    healthKey: "gemini",
    alternatives: ["openrouter", "openai", "anthropic"],
    url: "https://aistudio.google.com",
    docsUrl: "https://ai.google.dev/docs",
  },
  {
    id: "nvidia",
    name: "Nvidia NIM",
    category: "ai-models",
    description: "Nvidia NGC NIM microservices & inference API",
    logo: "nvidia",
    brandColor: "#76B900",
    envVars: ["NVIDIA_NGC_API_KEY"],
    costKey: "nvidia",
    healthKey: "nvidia",
    alternatives: ["openrouter", "openai", "gemini"],
    url: "https://build.nvidia.com",
  },
  {
    id: "tavily",
    name: "Tavily Search",
    category: "ai-models",
    description: "AI-native real-time web search and research API",
    logo: "tavily",
    brandColor: "#059669",
    envVars: ["TAVILY_API_KEY"],
    costKey: "tavily",
    alternatives: ["google"],
    url: "https://tavily.com",
  },
];

export const ACTIVE_SERVICE_IDS = INTEGRATION_SERVICES.filter(
  (s) => s.envVars.length > 0 && !s.id.includes("-"),
).map((s) => s.id);

export function getServiceById(id: string): IntegrationService | undefined {
  return INTEGRATION_SERVICES.find((s) => s.id === id);
}

export function getAlternativesFor(serviceId: string): IntegrationService[] {
  const service = getServiceById(serviceId);
  if (!service) return [];
  return service.alternatives
    .map((altId) => getServiceById(altId))
    .filter(Boolean) as IntegrationService[];
}

export function getServicesByCategory(category: string): IntegrationService[] {
  return INTEGRATION_SERVICES.filter((s) => s.category === category);
}

export const CATEGORIES: { id: string; label: string }[] = [
  { id: "version-control", label: "Version Control" },
  { id: "hosting", label: "Hosting & Deploy" },
  { id: "database", label: "Database" },
  { id: "cache", label: "Cache & Rate Limit" },
  { id: "cdn-security", label: "CDN & Security" },
  { id: "error-tracking", label: "Error Tracking" },
  { id: "email", label: "Email" },
  { id: "payments", label: "Payments" },
  { id: "ci-cd", label: "CI/CD" },
  { id: "testing", label: "Testing" },
  { id: "code-quality", label: "Code Quality" },
  { id: "auth", label: "Authentication" },
  { id: "analytics", label: "Analytics" },
  { id: "monitoring", label: "Monitoring" },
  { id: "bot-detection", label: "Bot Detection" },
  { id: "vault", label: "Secrets & Vault" },
  { id: "ai-models", label: "AI Models & Gateways" },
];
