-- Migration: Upsert all 44 confirmed LinkedIn outreach contacts ensuring full table integrity (v11.99 compliance)
-- Timestamp: 20260729000006
-- ROLLBACK: DELETE FROM public.linkedin_contacts WHERE full_name IN ('Yacine Jernite', 'Sean McGregor', 'Daniel Miessler', 'Rumman Chowdhury', 'Aviv Ovadya', 'Sven Cattell', 'Irene Solaiman');

INSERT INTO public.linkedin_contacts (full_name, title, category, profile_url, status)
VALUES
  ('Yacine Jernite', 'ML & Society Lead', 'Hugging Face', 'https://www.linkedin.com/in/yacine-jernite-997ba81b6/', 'added'),
  ('Sean McGregor', 'Founder', 'AI Incident Database', 'https://www.linkedin.com/in/seanbmcgregor/', 'added'),
  ('Daniel Miessler', 'Information Security Professional', 'Cybersecurity', 'https://www.linkedin.com/in/danielmiessler/', 'added'),
  ('Danqi Chen', 'Assistant Professor, Princeton NLP', 'NLP & Dense Retrieval', 'https://www.linkedin.com/in/danqic/', 'added'),
  ('Rumman Chowdhury', 'AI Ethicist & Data Scientist', 'AI Ethics Leader', 'https://www.linkedin.com/in/rumman/', 'added'),
  ('Aviv Ovadya', 'Researcher', 'Platform Democracy', 'https://www.linkedin.com/in/avivovadya/', 'added'),
  ('Sven Cattell', 'Founder', 'DEF CON AI Village', 'https://www.linkedin.com/in/sven-cattell-5748a311/', 'added'),
  ('Daniela Amodei', 'President & Co-Founder, Anthropic', 'AI Safety & Policy', '', 'added'),
  ('Dario Amodei', 'CEO & Co-Founder, Anthropic', 'AI Safety & Frontier Models', '', 'added'),
  ('Irene Solaiman', 'Head of Global Policy', 'Hugging Face', '', 'added'),
  ('Anca Dragan', 'Professor of CS, UC Berkeley & DeepMind', 'Human-Robot Interaction & Alignment', 'https://www.linkedin.com/in/ancadianadragan/', 'added'),
  ('Tristan Harris', 'Executive Director, Center for Humane Technology', 'Humane Tech & AI Ethics', 'https://www.linkedin.com/in/tristanjharris/', 'added'),
  ('Nick Bostrom', 'Professor & Author of Superintelligence', 'Philosophy & AI Risk', 'https://www.linkedin.com/in/nick-bostrom-b5272213a/', 'added'),
  ('Jack Clark', 'Co-Founder, Anthropic & Co-Chair, AI Index', 'AI Index & Public Policy', 'https://www.linkedin.com/in/jack-clark-10825b114/', 'added'),
  ('Yann LeCun', 'VP & Chief AI Scientist, Meta', 'AI Architecture & Open Science', '', 'added'),
  ('Samy Bengio', 'Senior Director of AI Research, Apple', 'Machine Learning Infrastructure', 'https://www.linkedin.com/in/bengio/', 'added'),
  ('Ilya Sutskever', 'Co-Founder, Safe Superintelligence Inc. (SSI)', 'Safe Superintelligence', '', 'added'),
  ('Andrej Karpathy', 'Founder, Eureka Labs & Ex-Tesla AI Director', 'AI Education & Neural Networks', '', 'added'),
  ('Jan Leike', 'AI Safety Researcher, Anthropic', 'Alignment & Superalignment', '', 'added'),
  ('Stuart Russell', 'Professor of CS, UC Berkeley & Author of Human Compatible', 'AI Safety Research', 'https://www.linkedin.com/in/stuartjonathanrussell/', 'added'),
  ('Max Tegmark', 'President, Future of Life Institute (FLI)', 'Existential Risk & Policy', 'https://www.linkedin.com/in/max-tegmark-68a99898/', 'added'),
  ('Joy Buolamwini', 'Founder, Algorithmic Justice League', 'AI Bias & Fairness', 'https://www.linkedin.com/in/buolamwini/', 'added'),
  ('Timnit Gebru', 'Founder, DAIR Institute', 'Distributed AI Research', 'https://www.linkedin.com/in/timnit-gebru-7b3b407/', 'added'),
  ('Margaret Mitchell', 'Chief Ethics Scientist, Hugging Face', 'AI Ethics & Open Models', 'https://www.linkedin.com/in/margaret-mitchell-9b13429/', 'added'),
  ('Percy Liang', 'Director, Center for Research on Foundation Models (CRFM)', 'HELM Benchmark & Foundation Models', 'https://www.linkedin.com/in/percy-liang-717b8a/', 'added'),
  ('Dawn Song', 'Professor of CS, UC Berkeley', 'AI Security & Privacy', 'https://www.linkedin.com/in/dawn-song-51586033/', 'added'),
  ('Pushmeet Kohli', 'VP of Research, Google DeepMind', 'AI Safety & Reliability', 'https://www.linkedin.com/in/pushmeet-kohli-4838994/', 'added'),
  ('Dan Boneh', 'Professor of CS & Electrical Engineering, Stanford', 'Applied Cryptography & AI Privacy', 'https://www.linkedin.com/in/dan-boneh-8b599020/', 'added'),
  ('Demis Hassabis', 'CEO & Co-Founder, Google DeepMind', 'Frontier AI & Science', 'https://www.linkedin.com/in/demishassabis/', 'added'),
  ('Arvind Narayanan', 'Professor of CS, Princeton University', 'AI Snake Oil & Privacy', 'https://www.linkedin.com/in/randomwalker/', 'added'),
  ('Sayash Kapoor', 'PhD Researcher, Princeton University', 'AI Accountability & Benchmarks', 'https://www.linkedin.com/in/ksayash/', 'added'),
  ('Chelsea Finn', 'Assistant Professor, Stanford University', 'Meta-Learning & Robotics', 'https://www.linkedin.com/in/cbfinn/', 'added'),
  ('Pieter Abbeel', 'Professor of CS, UC Berkeley & Covariant', 'Robotics & Reinforcement Learning', 'https://www.linkedin.com/in/pieterabbeel/', 'added'),
  ('Sergey Levine', 'Associate Professor, UC Berkeley', 'Offline RL & Decision Models', 'https://www.linkedin.com/in/sergey-levine-5a31a24/', 'added'),
  ('Christopher Manning', 'Director, Stanford AI Lab (SAIL)', 'NLP & Foundation Models', 'https://www.linkedin.com/in/christopher-manning-011575/', 'added'),
  ('Ellie Pavlick', 'Associate Professor, Brown University & OpenAI', 'Representation & Interpretability', 'https://www.linkedin.com/in/ellie-pavlick-5499b2270/', 'added'),
  ('Yejin Choi', 'Professor, University of Washington & Allen AI', 'Commonsense Reasoning & AI Ethics', 'https://www.linkedin.com/in/yejin-choi-0b900b1/', 'added'),
  ('Helen Toner', 'Director of Strategy, CSET Georgetown', 'AI Policy & Security', 'https://www.linkedin.com/in/helen-toner-226b8916/', 'added'),
  ('Paul Christiano', 'Founder, Alignment Research Center (ARC)', 'AI Alignment & Red-Teaming', 'https://www.linkedin.com/in/paul-christiano-5089211bb/', 'added'),
  ('Collin Burns', 'Researcher, OpenAI / ARC', 'Eliciting Latent Knowledge', 'https://www.linkedin.com/in/colin-burns-87a562171/', 'added'),
  ('Jared Kaplan', 'Co-Founder & Chief Scientist, Anthropic', 'Scaling Laws & Alignment', 'https://www.linkedin.com/in/jared-kaplan-645843213/', 'added'),
  ('Alexander Rush', 'Associate Professor, Cornell Tech & Hugging Face', 'Open NLP & Infrastructure', 'https://www.linkedin.com/in/alex-rush-992119161/', 'added'),
  ('Dan Hendrycks', 'Director, Center for AI Safety (CAIS)', 'AI Benchmarks & Risk Evaluation', 'https://www.linkedin.com/in/dan-hendrycks-04062395/', 'added'),
  ('Yoshua Bengio', 'Founder & Scientific Director, Mila', 'AI Safety & International Governance', '', 'added')
ON CONFLICT (full_name) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, profile_url = EXCLUDED.profile_url, status = EXCLUDED.status, updated_at = NOW();
